Handle CKError.changeTokenExpired
Delete stored token and retry request.

Fixes errors such as the following:
```
Error: Error fetching changes in zone <CKRecordZoneID: 0x151f6c9c0; ownerName=__defaultOwner__, zoneName=CarsZone>: client knowledge differs from server knowledge
```

Use UserDefaults.removeObject(forKey:) instead of NSObject.setNilValueForKey() because the latter raises an NSInvalidArgumentException.